---
title: "Lab_1"
author: "Callie Steffen,"
date: "1/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) ##means all code will show up, you can set for each chunk
```

```{r}

library(tidyverse)
library(here)
library(janitor)
library(kableExtra)



```
Read in noaa_fisheries.csv data
```{r}

##us_landings<-read_csv("data/noaa_fisheries.csv")

us_landings <- read_csv(here("data","noaa_fisheries.csv"))

```

now make a tidy version of dataframe
```{r}
landings_tidy <- us_landings %>%
  janitor::clean_names() %>% 
  mutate(state = str_to_lower(state),
         afs_name = str_to_lower(afs_name)) %>% 
  mutate(dollars_num = parse_number(dollars_usd))
  
```

lets get some information on salmon 


```{r}

##dont want the word aggregate, its not relevent (just means nothing comes after it first indicator(group)) 
##find all entries in afs that have salmon
##seperate out group and species by comma

salmon_landings <- landings_tidy %>%
  mutate(afs_clean = str_remove(afs_name, pattern = "aggregate")) %>%
  filter(str_detect(afs_clean, pattern = "salmon")) %>% 
  separate(afs_clean, into= c("group", "species") , sep =",")
  
```

Find some grouped summary data: 

Find annual total US landings and dollar value (summing across all states) for each TYPE of salmon using group_by() + summarize()
```{r}

salmon_summary <- salmon_landings%>% 
  group_by(year, species) %>%
  summarize(
    tot_landings =sum(landings_pounds),
    tot_value = sum(dollars_num)
  )
  

```

Graphing Results

```{r}
salmon_landings_graph <- ggplot(data = salmon_summary,
                                aes(x = year,y=tot_landings)) +
  geom_line(aes(color = species)) +
  theme_minimal()

salmon_landings_graph

```

Now we will export our graph with ggsave
```{r}

ggsave(plot = salmon_landings_graph ,
       here("figures" , "us_salmon_cs.png") ,
       height = 5,
       width = 8)

```

Make a chart of 1st 5 entries
```{r}

salmon_first_5 <- salmon_summary %>% 
  head(5)

```

use kable:
```{r}

kable(salmon_first_5) %>% 
  kable_styling(bootstrap_options = "striped",full_width = FALSE)


```

